version: '3'
services:
  main:
    restart: always
    depends_on:
      - mongo
    build:
      context: .
   
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
 
volumes:
 mongodb:
#  rabbitmq_data: